[package]
name = "rnn"
version = "0.1.0"
edition = "2024"

[dependencies]

candle-core = {workspace = true}
candle-nn = {workspace = true}
anyhow = {workspace = true}
#candle-datasets = {workspace = true}
#clap = {workspace = true}
rand.workspace = true
#image.workspace=  true
