[package]
name = "mnist_cnn"
version = "0.1.0"
edition = "2021"
[dependencies]
candle-core = {workspace = true}
candle-nn = {workspace = true}
anyhow = {workspace = true}
candle-datasets = {workspace = true}
clap = {workspace = true}
rand.workspace = true
image.workspace=  true